<footer class="footer-distributed">

    <div class="footer-right">

        <a href="https://fr-fr.facebook.com/"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com/?lang=fr"><i class="fa fa-twitter"></i></a>
        <a href="https://fr.linkedin.com"><i class="fa fa-linkedin"></i></a>
        <a href="https://github.com/"><i class="fa fa-github"></i></a>

    </div>

    <div class="footer-left">

        <p class="footer-links">
            <a class="link-1" href="../vuescontroleurs/accueil.php"> Accueil </a>
            <a href="../vuescontroleurs/listedesbiens.php."> Liste des biens </a>
            <a href="../vuescontroleurs/contact.php"> Contact </a>
        </p>

        <p>Lille Immo &copy; 2022</p>
    </div>

</footer>

</body>
</html>


